librarystore2.2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cart/index'
  resources :items
  get '/home' => 'staticpages#home'
  get '/books' => 'staticpages#books'
  get '/about' => 'staticpages#about'
  get '/contact' => 'staticpages#contact'
  get '/faq' => 'staticpages#faq'
  
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  post '/search' => 'items#search'
  
  root :to => 'site#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

librarystore2.2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

librarystore2.2/app/models/item.rb
class Item < ApplicationRecord
end

librarystore2.2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

librarystore2.2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

librarystore2.2/app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  def add
    id = params[:id]
      if session[:cart] then
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end
      
      if cart[id] then
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end

    redirect_to :action => :index
    
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end

  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
  end
  
end
end

librarystore2.2/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def search
    @search_term = params[:q]
    st = "%#{params[:q]}%"
    @items = Item.where("title like?", st)
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :author, :synopsis, :price, :image_url, :category)
    end
end

librarystore2.2/app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    @items = Item.all
  end
  
  def books
  end

  def about
  end

  def contact
  end

  def faq
  end
end

librarystore2.2/app/controllers/user_controller.rb
class UserController < ApplicationController
    def login
    end
    
    def login
        session[:login] = 1
        session[:cart] = nil
        flash[:notice] = "Admin logged in sucessfully!"
        redirect_to :controller => :items
    end

    def logout
        session[:login] = nil
        session[:cart] = nil
        flash[:notice] = "You have been successfully logged out!"
        redirect_to :controller => :items
    end

end

librarystore2.2/app/helpers/application_helper.rb
module ApplicationHelper
end

librarystore2.2/app/helpers/cart_helper.rb
module CartHelper
end

librarystore2.2/app/helpers/items_helper.rb
module ItemsHelper
end

librarystore2.2/app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

librarystore2.2/app/helpers/user_helper.rb
module UserHelper
end

librarystore2.2/app/views/cart/index.html.erb
<% if @cart.empty? %>
<p>Your cart is empty!</p>
<% end %>

librarystore2.2/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

librarystore2.2/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

librarystore2.2/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">

<h1>Books</h1>

    <% @items.each do |item| %>
    <div class="itemhols">
       <h1><%= link_to (item.title), item %></h1>
       <p><%=item.author %></p>
       <p><%=item.synopsis %></p>
       <p>Price<%= number_to_currency(item.price, :unit => "€") %>
       <br>
       Category: <%= item.category %>
       </p>
       
       <p>
        <%= link_to 'Show', item, :class => "button", :role => "button" %>
        
        <% if session[:login] == 1 %>
        <%= link_to 'Edit', edit_item_path(item), :class => "button", :role => "button" %>
        <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Do you want to delete this item?' }, :class => "button", :role => "button" %>
        <% end %>
        
        <%= link_to 'Buy', cart_path, :class => "button", :role => "button" %>
        <%= link_to 'Rent', cart_path, :class => "button", :role => "button" %>
        </p>
     </div>   
     
     
</div>     
<% end %>
     
<br>
<% if session[:login] == 1 %>
<%= link_to 'New Item', new_item_path, :class => "button", :role => "button" %>

<% end %>

librarystore2.2/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

librarystore2.2/app/views/items/search.html.erb
<h2>You searched for <%= @search_term %></h2>

<% if @items.length == 0 %>
<br/>
<h2>We are sorry. No books were found to match your search.</h2>
<% end %>

<table class="catalog">
    <% @items.each do |item| %>
    <tr>
        <td>
            <div class="title">
                <%= link_to item.title, item %>
            </div>
            <div class="synopsis">
                <%= item.synopsis %>
            </div>
            <div class="price">
                <%= number_to_currency(item.price, :unit => "€") %>
            </div>
            <div class="links">
                <% if user_signed_in? %>
                <%= link_to 'Edit', edit_item_path(item) %>
                <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Do you want to delete this item?' } %>
                <% else %>
                
                <a href="/cart/<%= item.id %>">Add to Cart</a>
                <% end %>
            </div>
        </td>
    </tr>
    <% end %>
</table>

librarystore2.2/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">

<h1><%= @item.title %></h1>

<p>
  <strong>Author:</strong>
  <%= @item.author %>
</p>

<%= image_tag @item.image_url, :class => 'welcomlm' %>

<p>
  <%= @item.synopsis %>
</p>

  <div class="itemhols">
  <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
  <br>
  Category: <%= @item.category %></p>

  <p>
  <%= link_to 'Buy', cart_path, :class => "button", :role => "button" %>
  <%= link_to 'Rent', cart_path, :class => "button", :role => "button" %>
  <%= link_to 'Back', items_path, :class => "button", :role => "button" %>
  <% if session[:login] == 1 %>
  <%= link_to 'Edit', edit_item_path(@item), :class => "button", :role => "button" %>
  <% end %>
  </p>

  </div>
</div>

librarystore2.2/app/views/layouts/_popular.html.erb
<table class="catalog">
    <% @items.limit(3).order(:id).each do |item| %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
            </div>
            <div class="title">
                <%= link_to item.title, item %>
            </div>
            <div class="synopsis">
                <%= item.synopsis %>
            </div>
            <div class="price">
                <%= number_to_currency(item.price, :unit => "€") %>
            </div>
            <div class="links">
                <% if session[:login] == 1 %>
                <%= link_to 'Edit', edit_item_path(item) %>
                <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Do you want to delete this item?'} %>
                <% else %>
                

                <% end %>
            </div>
        </td>
    </tr>
    <% end %>
</table>

librarystore2.2/app/views/layouts/_search.html.erb
<div class="search">
<%= form_tag("/search", :method => "post") do %>
<%= label_tag("Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>
</div>

librarystore2.2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= yield(:title) %> | Enlighten your soul</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
    
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      
      <header class="headSec">
          <ul>
            <li><%=link_to "Home", home_path %></li>
            <li><%=link_to "Books", items_path %></li>
            <li><%=link_to "About us", about_path %></li>
            <li><%=link_to "Contact us", contact_path %></li>
            <li><%=link_to "FAQ's", faq_path %></li>
            
            <% if user_signed_in? %>
            <li><a href="#">Welcome, <%= current_user.email %></a></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
            <li><%= link_to 'Register', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
            
            <% if session[:login] == 1 %>
            <li><%=link_to "Admin Logout", logout_path %></li>
            <% else %>
            <li><%=link_to "Admin Login", login_path %></li>
            <% end %>
            
            <li><%=link_to "Cart", cart_path %></li>
          </ul>
          <%=render 'layouts/search'%>
      </header>
      
  </head>

    <div class="container">
      <%=yield %>
    </div>
  
    <footer class="footer">
        <p>The Lantern Center - 15, Synge Street, Dublin 8 - Ireland</p>
        <p>spiritismireland@gmail.com</p>
        <p>&copy;2018 Spiritism Society of Ireland</p>
      </footer>
  
</html>

librarystore2.2/app/views/staticpages/about.html.erb
<% provide(:title, "About us") %>

<h1>About us</h1>

<p>The Spiritism Society of Ireland - SSI is an independent, non-profit Spiritist Group, established in Dublin since 2009, that aims to study, practice and bring to Ireland the Spiritist Doctrine as codified by Allan Kardec in three foundational aspects: Philosophical, Religious and Scientific.</p>
<p>We have healing sessions, public meetings, children's gospel and gospel studies group.</p>
<p>Healing Sessions: Sundays from 10:45 am to 11:15 am</p>
<p>Public Meetings & Children's Gospel: Sundays from 11:15 am to 12 pm</p>
<p>Gospel Study Group: Tuesdays from 7 pm to 9 pm</p>

librarystore2.2/app/views/staticpages/books.html.erb
<% provide(:title, "Books") %>

librarystore2.2/app/views/staticpages/contact.html.erb
<% provide(:title, "Contact us") %>

<h1>Contact us</h1>
<p>You can find our Library at The Lantern Centre - 15, Synge Street, Dublin 8 - Ireland every Sunday from 10:30 am to 12:30 pm.</p>
<p>Webpage: http://www.spiritismireland.com</p>
<p>Facebook page: https://www.facebook.com/SpiritistSocietyIreland/</p>

librarystore2.2/app/views/staticpages/faq.html.erb
<% provide(:title, "FAQ's") %>

<h1>Frequent Asked Questions</h1>

<p><strong>How can I rent a book?</strong></p>
<p>To rent a book you can visit us at The Lantern Center every Sunday (except before Bank Holidays) or you can browse on our website. After you select your book to be rented you will be asked to register in our page or login in your account. You will then be able to reserve your book to be rented. Unfortunately we are not able to deliver the books at the moment so you will need to go to The Lantern Center in one of the days we are there (Sunday or Tuesday) and collect your books. You will find the times we are open in our Contact Page.</p>
<p><strong>How can I buy a book?</strong></p>
<p>The process to buy a book is very similar to rent a book but at The Lantern Center you will process the payment. At the moment we only accept cash. To see the times we are at The Lantern Center visit our Contact Page.</p>
<p><strong>How many days can I keep the book I rent for?</strong></p>
<p>You can keep the book you rent for up to 4 weeks. Is it possible to renew the renting. Just inform us at The Lantern Center or send us an e-mail. Wait for the confirmation to be sure that you will be able to renew the renting. Some times we have a waiting list but we will be glad to let you now for how long you can keep the book with yourself.</p>
<p><strong>Do you delivery the books?</strong></p>
<p></p>Unfortunately we are not able to deliver the books at the moment. They need to be collected at The Lantern Center.
<p><strong>Can I return the book I bought?</strong></p>
<p></p>Yes, you can. You have 2 weeks to bring the book back to us. The book will need to be inspected and the return will be agreed with the president of the Spiritist Society of Ireland or the manager of the library.</p>
<p><strong>If you still have any doubts do not hesitate and send us a message or call us. We will be very happy to help you!</strong></p>

librarystore2.2/app/views/staticpages/home.html.erb
<% provide(:title, "Home") %>

<div class="home">
    <p><strong>Welcome to the</strong></p>
    <h1>Spiritism Society of Ireland Library</h1>
</div>

<div class="home_image">
      <%=yield %>
</div>

<%=render 'layouts/popular'%>